server:
  port: 8086
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 124.222.105.11:8848
    service-registry:
      auto-registration:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: product_route
          uri: http://localhost:8084/
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}