spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
    url: jdbc:mysql://sh-cdb-dckrz0zs.sql.tencentcdb.com:58955/mall_oms
  cloud:
    nacos:
      server-addr: 124.222.105.11:8848
    service-registry:
      auto-registration:
        enabled: true
  application:
    name: order
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8083